<?php
/*
Author: Luis del Cid
Author URI: https://github.com/luisdelcid
Description: A collection of useful functions for your WordPress plugins or theme's functions.php.
Domain Path:
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Network: true
Plugin Name: LDC Functions
Plugin URI: https://github.com/luisdelcid/ldc-functions
Text Domain: ldc-functions
Version: 0.2.19
*/

if(defined('ABSPATH')){
    register_activation_hook(__FILE__, function(){
        $content = <<<EOF
<?php
/*
Author: Luis del Cid
Author URI: https://github.com/luisdelcid
Description: This is automatically generated by the LDC Functions plugin. It is automatically disabled when disabling the main plugin.
Domain Path:
License: GPL2
License URI: https://www.gnu.org/licenses/gpl-2.0.html
Network: true
Plugin Name: LDC Preloader
Plugin URI: https://github.com/luisdelcid/ldc-preloader
Text Domain: ldc-preloader
Version:
*/

if(defined('WP_PLUGIN_DIR') and function_exists('trailingslashit')){
    if(file_exists(trailingslashit(WP_PLUGIN_DIR) . 'ldc-functions/ldc-functions.php')){
        if((function_exists('get_option') and in_array('ldc-functions/ldc-functions.php', (array) get_option('active_plugins'))) or (function_exists('get_site_option') and array_key_exists('ldc-functions/ldc-functions.php', (array) get_site_option('active_sitewide_plugins')))){
            $ldc_dir = trailingslashit(WP_PLUGIN_DIR) . 'ldc-functions/';
            foreach(glob($ldc_dir . 'functions/*', GLOB_ONLYDIR) as $ldc_dir){
                if(file_exists($ldc_dir . '/functions.php')){
                    require_once($ldc_dir . '/functions.php');
                }
            }
            unset($ldc_dir);
            ldc_do('ldc_functions_preloaded');
        }
    }
}

EOF;
        $file = trailingslashit(WPMU_PLUGIN_DIR) . 'ldc-preloader.php';
        if(file_exists($file) and md5($content) == md5_file($file)){
            return;
        }
        if(wp_mkdir_p(WPMU_PLUGIN_DIR)){
            @file_put_contents($file, $content);
        }
    });
    register_deactivation_hook(__FILE__, function(){
        $file = trailingslashit(WPMU_PLUGIN_DIR) . 'ldc-preloader.php';
        if(!file_exists($file)){
            return;
        }
        @unlink($file);
    });
    $ldc_file = trailingslashit(WPMU_PLUGIN_DIR) . 'ldc-preloader.php';
    if(file_exists($ldc_file)){
        ldc_enqueue_functions('admin');
        ldc_enqueue_functions('front-end');
        ldc_on('after_setup_theme', function(){
            $file = get_stylesheet_directory() . '/ldc-functions.php';
            if(file_exists($file)){
                require_once($file);
            }
        });
        ldc_on('plugins_loaded', function(){
            ldc_build_update_checker('https://github.com/luisdelcid/ldc-functions', __FILE__, 'ldc-functions');
            ldc_do('ldc_functions_loaded');
        });
    }
    unset($ldc_file);
}
